# Generated by Django 6.0.6 on 2026-09-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_promotions'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterModelOptions(
            name='promotionproduct',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Promotion Product', 'verbose_name_plural': 'Promotion Products'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='badge_text',
            field=models.CharField(blank=True, help_text="Optional hero badge override, e.g. 'Flash Sale'. Leave blank to use the default label for the promotion's current state.", max_length=60),
        ),
        migrations.AddField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='products.category'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, help_text='Longer copy — used lower on the page if the template needs it.'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='short_description',
            field=models.CharField(blank=True, help_text='Hero subheading / one-line pitch.', max_length=255),
        ),
    ]
