"""
services/buyer_pdf.py

Dedicated ReportLab service for generating MarketSphere Buyer Profile reports.
"""
from io import BytesIO
from django.utils import timezone

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
)

# =============================================================
# BRAND & STYLE CONSTANTS
# =============================================================
ACCENT_COLOR = colors.HexColor("#9D6638")
HEADING_COLOR = colors.HexColor("#4E220F")
MUTED_COLOR = colors.HexColor("#6B6B6B")
BORDER_COLOR = colors.HexColor("#D9D2C4")
LIGHT_BG = colors.HexColor("#F7F1DE")

PAGE_MARGIN = 20 * mm


def _get_styles():
    """Defines the typography system for the report."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="ReportBrand",
        fontName="Helvetica-Bold",
        fontSize=20,
        textColor=HEADING_COLOR,
        spaceAfter=4,
    ))

    styles.add(ParagraphStyle(
        name="ReportTitle",
        fontName="Helvetica",
        fontSize=12,
        spaceBefore=4,
        textColor=MUTED_COLOR,
    ))

    styles.add(ParagraphStyle(
        name="MetaRight",
        fontName="Helvetica",
        fontSize=9,
        textColor=MUTED_COLOR,
        alignment=TA_RIGHT,
        leading=12,
    ))

    styles.add(ParagraphStyle(
        name="SectionHeading",
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=HEADING_COLOR,
        spaceBefore=15,
        spaceAfter=6,
    ))

    styles.add(ParagraphStyle(
        name="KeyStyle",
        fontName="Helvetica-Bold",
        fontSize=9,
        textColor=HEADING_COLOR,
    ))

    styles.add(ParagraphStyle(
        name="ValueStyle",
        fontName="Helvetica",
        fontSize=9,
        textColor=colors.black,
    ))
    
    styles.add(ParagraphStyle(
        name="NotesBody",
        fontName="Helvetica",
        fontSize=9,
        textColor=colors.black,
        leading=14,
    ))

    return styles


# =============================================================
# DATA EXTRACTION HELPERS (Graceful Fallbacks)
# =============================================================
def _get_attr(obj, attrs, default="—"):
    """Safely retrieves the first available attribute from a list."""
    for attr in attrs:
        if hasattr(obj, attr):
            val = getattr(obj, attr)
            if val not in [None, ""]:
                if hasattr(val, 'strftime'):
                    return val.strftime("%b %d, %Y %H:%M")
                return str(val)
    return default


def _get_related_manager(obj, names):
    """Safely retrieves a related manager by checking common naming patterns."""
    for name in names:
        if hasattr(obj, name):
            return getattr(obj, name)
    return None


def _format_currency(value):
    try:
        return f"Rs. {float(value or 0):,.2f}"
    except (TypeError, ValueError):
        return "Rs. 0.00"


# =============================================================
# DOCUMENT BUILDERS
# =============================================================
def _draw_footer(canvas, doc):
    """Canvas hook for drawing the universal footer on every page."""
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED_COLOR)
    
    timestamp = timezone.localtime().strftime("%Y-%m-%d %H:%M:%S")
    
    canvas.drawString(PAGE_MARGIN, 10 * mm, f"Generated by MarketSphere Admin Dashboard | {timestamp}")
    canvas.drawCentredString(A4[0] / 2.0, 10 * mm, "Confidential Document")
    canvas.drawRightString(A4[0] - PAGE_MARGIN, 10 * mm, f"Page {doc.page}")
    
    canvas.restoreState()


def _build_kv_table(data_list, styles):
    """Renders a structured 4-column Key-Value grid."""
    rows = []
    # Process items in chunks of 2 for a two-column (4 sub-columns) layout
    for i in range(0, len(data_list), 2):
        row = []
        # First Pair
        item1 = data_list[i]
        row.extend([Paragraph(item1[0], styles["KeyStyle"]), Paragraph(item1[1], styles["ValueStyle"])])
        
        # Second Pair (if exists)
        if i + 1 < len(data_list):
            item2 = data_list[i+1]
            row.extend([Paragraph(item2[0], styles["KeyStyle"]), Paragraph(item2[1], styles["ValueStyle"])])
        else:
            row.extend([Paragraph("", styles["KeyStyle"]), Paragraph("", styles["ValueStyle"])])
            
        rows.append(row)
        
    table = Table(rows, colWidths=[35*mm, 50*mm, 35*mm, 50*mm])
    table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
    ]))
    return table


# =============================================================
# SECTION GENERATORS
# =============================================================
def generate_buyer_profile_pdf(buyer, admin_user):
    """
    Main orchestration function. Builds the ReportLab document flow and 
    returns a BytesIO buffer containing the PDF.
    """
    buffer = BytesIO()
    styles = _get_styles()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=PAGE_MARGIN, rightMargin=PAGE_MARGIN,
        topMargin=PAGE_MARGIN, bottomMargin=PAGE_MARGIN,
        title=f"Buyer Profile - {getattr(buyer, 'username', 'User')}"
    )
    
    elements = []
    
    # --- HEADER ---
    brand_block = [
        Paragraph("MARKETSPHERE", styles["ReportBrand"]),
        Paragraph("Buyer Profile Report", styles["ReportTitle"]),
    ]
    
    meta_block = [
        Paragraph(f"<b>Generated Date:</b> {timezone.now().strftime('%b %d, %Y')}", styles["MetaRight"]),
        Paragraph(f"<b>Time:</b> {timezone.now().strftime('%H:%M:%S')}", styles["MetaRight"]),
        Paragraph(f"<b>Admin:</b> {_get_attr(admin_user, ['get_full_name', 'username'], 'System')}", styles["MetaRight"]),
    ]
    
    header_table = Table([[brand_block, meta_block]], colWidths=[100*mm, 70*mm])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
    ]))
    
    elements.extend([
        header_table,
        Spacer(1, 10),
        HRFlowable(width="100%", thickness=1.5, color=ACCENT_COLOR, spaceAfter=15)
    ])
    
    # --- BUYER INFORMATION ---
    elements.append(Paragraph("BUYER INFORMATION", styles["SectionHeading"]))
    
    full_name = buyer.get_full_name() if hasattr(buyer, 'get_full_name') and buyer.get_full_name() else "—"
    status_str = "Active" if getattr(buyer, 'is_active', True) else "Inactive/Suspended"
    
    buyer_info = [
        ("Full Name", full_name),
        ("Username", _get_attr(buyer, ['username'])),
        ("Email", _get_attr(buyer, ['email'])),
        ("Phone Number", _get_attr(buyer, ['phone_number', 'phone', 'contact'])),
        ("Account Status", status_str),
        ("Email Verified", "Yes" if getattr(buyer, 'is_email_verified', False) else "No"),
        ("Joined Date", _get_attr(buyer, ['date_joined', 'created_at'])),
        ("Last Login", _get_attr(buyer, ['last_login'])),
    ]
    elements.extend([_build_kv_table(buyer_info, styles), Spacer(1, 15)])
    
    # --- ADDRESS INFORMATION ---
    elements.append(KeepTogether([
        Paragraph("ADDRESS INFORMATION", styles["SectionHeading"]),
    ]))
    
    addr_manager = _get_related_manager(buyer, ['address_set', 'addresses', 'useraddress_set'])
    primary_addr = None
    if addr_manager:
        addresses = list(addr_manager.all())
        primary_addr = next((a for a in addresses if getattr(a, 'is_default', getattr(a, 'is_primary', False))), None)
        if not primary_addr and addresses:
            primary_addr = addresses[0]
            
    if primary_addr:
        addr_info = [
            ("Primary Address", _get_attr(primary_addr, ['street_address', 'address_line_1', 'address'])),
            ("Address Type", _get_attr(primary_addr, ['address_type', 'type'], "Standard")),
            ("City", _get_attr(primary_addr, ['city'])),
            ("Province / State", _get_attr(primary_addr, ['state', 'province'])),
            ("Postal Code", _get_attr(primary_addr, ['postal_code', 'zip_code'])),
            ("Country", _get_attr(primary_addr, ['country'])),
        ]
        elements.append(_build_kv_table(addr_info, styles))
    else:
        elements.append(Paragraph("<i>No address information found on record.</i>", styles["ValueStyle"]))
    
    elements.append(Spacer(1, 15))
    
    # --- ORDER SUMMARY ---
    elements.append(KeepTogether([
        Paragraph("ORDER SUMMARY", styles["SectionHeading"]),
    ]))
    
    orders_manager = _get_related_manager(buyer, ['order_set', 'orders'])
    order_stats = {
        "Total Orders": 0, "Completed": 0, "Pending": 0, "Cancelled": 0, "Returned": 0,
        "Total Spent": 0.0, "Dates": []
    }
    
    if orders_manager:
        for order in orders_manager.all():
            order_stats["Total Orders"] += 1
            status = str(getattr(order, 'status', '')).lower()
            
            if 'complete' in status or 'deliver' in status: order_stats["Completed"] += 1
            elif 'pend' in status or 'process' in status: order_stats["Pending"] += 1
            elif 'cancel' in status: order_stats["Cancelled"] += 1
            elif 'return' in status: order_stats["Returned"] += 1
            
            # Accommodate typical e-commerce money field names
            amount = float(getattr(order, 'total_amount', getattr(order, 'total', getattr(order, 'grand_total', 0))))
            order_stats["Total Spent"] += amount
            
            created = getattr(order, 'created_at', getattr(order, 'date_created', None))
            if created:
                order_stats["Dates"].append(created)

    aov = (order_stats["Total Spent"] / order_stats["Total Orders"]) if order_stats["Total Orders"] > 0 else 0
    order_stats["Dates"].sort()
    
    order_info = [
        ("Total Orders", str(order_stats["Total Orders"])),
        ("Total Amount Spent", _format_currency(order_stats["Total Spent"])),
        ("Completed Orders", str(order_stats["Completed"])),
        ("Average Order Value", _format_currency(aov)),
        ("Pending Orders", str(order_stats["Pending"])),
        ("First Order Date", order_stats["Dates"][0].strftime("%b %d, %Y") if order_stats["Dates"] else "—"),
        ("Cancelled / Returned", f"{order_stats['Cancelled']} / {order_stats['Returned']}"),
        ("Latest Order Date", order_stats["Dates"][-1].strftime("%b %d, %Y") if order_stats["Dates"] else "—"),
    ]
    elements.extend([_build_kv_table(order_info, styles), Spacer(1, 15)])
    
    # --- ACCOUNT ACTIVITY ---
    elements.append(KeepTogether([
        Paragraph("ACCOUNT ACTIVITY", styles["SectionHeading"]),
    ]))
    
    wishlists = _get_related_manager(buyer, ['wishlist_set', 'wishlists'])
    reviews = _get_related_manager(buyer, ['review_set', 'reviews'])
    
    activity_info = [
        ("Wishlist Items", str(wishlists.count()) if wishlists else "0"),
        ("Reviews Written", str(reviews.count()) if reviews else "0"),
        ("Saved Addresses", str(addr_manager.count()) if addr_manager else "0"),
        ("Products Purchased", "Calculated on demand"), # Placeholder if strict DB aggregation isn't available
    ]
    elements.extend([_build_kv_table(activity_info, styles), Spacer(1, 15)])
    
    # --- SECURITY ---
    elements.append(KeepTogether([
        Paragraph("SECURITY", styles["SectionHeading"]),
    ]))
    
    # Checking for common 2FA app relationships
    has_2fa = (
        hasattr(buyer, 'totpdevice_set') and buyer.totpdevice_set.filter(confirmed=True).exists()
    ) or getattr(buyer, 'has_2fa', False)
    
    security_info = [
        ("Email Verified", "Yes" if getattr(buyer, 'is_email_verified', False) else "No"),
        ("Account Status", status_str),
        ("Two-factor Auth", "Enabled" if has_2fa else "Disabled"),
        ("Last Login", _get_attr(buyer, ['last_login'])),
        ("Password Usable", "Yes" if buyer.has_usable_password() else "No (OAuth / Invalid)"),
    ]
    elements.extend([_build_kv_table(security_info, styles), Spacer(1, 15)])
    
    # --- ADMIN NOTES ---
    elements.append(KeepTogether([
        Paragraph("ADMIN NOTES", styles["SectionHeading"]),
    ]))
    
    admin_notes = _get_attr(buyer, ['admin_notes', 'notes', 'internal_notes'], None)
    if admin_notes and admin_notes != "—":
        elements.append(Paragraph(admin_notes.replace('\n', '<br/>'), styles["NotesBody"]))
    else:
        elements.append(Paragraph("<i>No admin notes available for this buyer profile.</i>", styles["NotesBody"]))

    # Build the document
    doc.build(elements, onFirstPage=_draw_footer, onLaterPages=_draw_footer)
    
    buffer.seek(0)
    return buffer