"""
services/seller_pdf.py

Dedicated ReportLab service for generating MarketSphere Seller Profile reports,
matching the exact design system and structure of buyer_pdf.py.
"""
from io import BytesIO
import datetime
from django.utils import timezone
from django.http import HttpResponse
from django.db.models import Sum, Count, Q, FloatField
from django.db.models.functions import Coalesce

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
)

# NOTE: Adjust these imports based on your actual app structure
from accounts.models import Seller
from orders.models import Order, OrderItem
from products.models import Product


# =============================================================
# BRAND & STYLE CONSTANTS (Matching buyer_pdf.py)
# =============================================================
ACCENT_COLOR = colors.HexColor("#9D6638")
HEADING_COLOR = colors.HexColor("#4E220F")
MUTED_COLOR = colors.HexColor("#6B6B6B")
BORDER_COLOR = colors.HexColor("#D9D2C4")
LIGHT_BG = colors.HexColor("#F7F1DE")

PAGE_MARGIN = 20 * mm


def _get_styles():
    """Defines the typography system for the report matching buyer_pdf.py."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="ReportBrand",
        fontName="Helvetica-Bold",
        fontSize=20,
        textColor=HEADING_COLOR,
        spaceAfter=4,
    ))

    styles.add(ParagraphStyle(
        name="ReportTitle",
        fontName="Helvetica",
        fontSize=12,
        spaceBefore=4,
        textColor=MUTED_COLOR,
    ))

    styles.add(ParagraphStyle(
        name="MetaRight",
        fontName="Helvetica",
        fontSize=9,
        textColor=MUTED_COLOR,
        alignment=TA_RIGHT,
        leading=12,
    ))

    styles.add(ParagraphStyle(
        name="SectionHeading",
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=HEADING_COLOR,
        spaceBefore=15,
        spaceAfter=6,
    ))

    styles.add(ParagraphStyle(
        name="KeyStyle",
        fontName="Helvetica-Bold",
        fontSize=9,
        textColor=HEADING_COLOR,
    ))

    styles.add(ParagraphStyle(
        name="ValueStyle",
        fontName="Helvetica",
        fontSize=9,
        textColor=colors.black,
    ))
    
    styles.add(ParagraphStyle(
        name="NotesBody",
        fontName="Helvetica",
        fontSize=9,
        textColor=colors.black,
        leading=14,
    ))

    styles.add(ParagraphStyle(
        name="TableHeader",
        fontName="Helvetica-Bold",
        fontSize=9,
        textColor=colors.white,
        alignment=TA_CENTER
    ))

    styles.add(ParagraphStyle(
        name="TableCell",
        fontName="Helvetica",
        fontSize=9,
        textColor=colors.black,
        leading=12,
        alignment=TA_CENTER
    ))

    styles.add(ParagraphStyle(
        name="TableCellLeft",
        parent=styles["TableCell"],
        alignment=TA_LEFT
    ))

    styles.add(ParagraphStyle(
        name="TableCellRight",
        parent=styles["TableCell"],
        alignment=TA_RIGHT
    ))

    return styles


# =============================================================
# DATA EXTRACTION & FORMATTING HELPERS
# =============================================================
def _get_attr(obj, attrs, default="—"):
    """Safely retrieves the first available attribute from a list."""
    for attr in attrs:
        if hasattr(obj, attr):
            val = getattr(obj, attr)
            if val not in [None, ""]:
                if hasattr(val, 'strftime'):
                    return val.strftime("%b %d, %Y %H:%M")
                return str(val)
    return default


def _format_currency(value):
    try:
        return f"Rs. {float(value or 0):,.2f}"
    except (TypeError, ValueError):
        return "Rs. 0.00"


def _yes_no(value):
    return "Yes" if value else "No"


def _safe_str(value, default="—"):
    if value is None or str(value).strip() == "":
        return default
    return str(value)


# =============================================================
# DOCUMENT BUILDERS & FOOTER HOOK
# =============================================================
def _draw_footer(canvas, doc):
    """Canvas hook for drawing the universal footer on every page matching buyer_pdf.py."""
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED_COLOR)
    
    timestamp = timezone.localtime().strftime("%Y-%m-%d %H:%M:%S")
    
    canvas.drawString(PAGE_MARGIN, 10 * mm, f"Generated by MarketSphere Admin Dashboard | {timestamp}")
    canvas.drawCentredString(A4[0] / 2.0, 10 * mm, "Confidential Document")
    canvas.drawRightString(A4[0] - PAGE_MARGIN, 10 * mm, f"Page {doc.page}")
    
    canvas.restoreState()


def _build_kv_table(data_list, styles):
    """Renders a structured 4-column Key-Value grid matching buyer_pdf.py."""
    rows = []
    for i in range(0, len(data_list), 2):
        row = []
        item1 = data_list[i]
        row.extend([Paragraph(item1[0], styles["KeyStyle"]), Paragraph(str(item1[1]), styles["ValueStyle"])])
        
        if i + 1 < len(data_list):
            item2 = data_list[i+1]
            row.extend([Paragraph(item2[0], styles["KeyStyle"]), Paragraph(str(item2[1]), styles["ValueStyle"])])
        else:
            row.extend([Paragraph("", styles["KeyStyle"]), Paragraph("", styles["ValueStyle"])])
            
        rows.append(row)
        
    table = Table(rows, colWidths=[35*mm, 50*mm, 35*mm, 50*mm])
    table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
    ]))
    return table


def _build_data_table(headers, row_data, col_widths, styles, align_left_cols=None, align_right_cols=None):
    """Builds a formatted list table with alternating row colors matching the theme."""
    align_left_cols = align_left_cols or []
    align_right_cols = align_right_cols or []
        
    table_data = []
    
    header_row = []
    for header in headers:
        header_row.append(Paragraph(header, styles["TableHeader"]))
    table_data.append(header_row)
    
    if not row_data:
        empty_row = [Paragraph("<i>No data available</i>", styles["TableCellLeft"])] + [""] * (len(headers) - 1)
        table_data.append(empty_row)
    else:
        for row in row_data:
            formatted_row = []
            for idx, cell_value in enumerate(row):
                if idx in align_left_cols:
                    style = styles["TableCellLeft"]
                elif idx in align_right_cols:
                    style = styles["TableCellRight"]
                else:
                    style = styles["TableCell"]
                formatted_row.append(Paragraph(str(cell_value), style))
            table_data.append(formatted_row)
            
    t = Table(table_data, colWidths=col_widths, repeatRows=1)
    
    t_style = [
        ('BACKGROUND', (0, 0), (-1, 0), HEADING_COLOR),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('BOX', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, BORDER_COLOR),
    ]
    
    if row_data:
        t_style.append(('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, LIGHT_BG]))
        
    t.setStyle(TableStyle(t_style))
    return t


# =============================================================
# MAIN ORCHESTRATION FUNCTION
# =============================================================
def export_seller_profile_snapshot(seller, admin_user=None):
    """
    Main orchestration function. Builds the ReportLab document flow and 
    returns an HttpResponse containing the Seller Profile PDF snapshot.
    """
    buffer = BytesIO()
    styles = _get_styles()
    
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=PAGE_MARGIN, rightMargin=PAGE_MARGIN,
        topMargin=PAGE_MARGIN, bottomMargin=PAGE_MARGIN,
        title=f"Seller Profile - {getattr(seller, 'store_name', 'Store')}"
    )
    
    user = getattr(seller, 'user', None)
    profile = getattr(seller, 'profile', None)
    settings = getattr(seller, 'settings', None)
    address = getattr(seller, 'business_address', None)
    
    elements = []
    
    # --- HEADER ---
    brand_block = [
        Paragraph("MARKETSPHERE", styles["ReportBrand"]),
        Paragraph("Seller Profile Report", styles["ReportTitle"]),
    ]
    
    meta_block = [
        Paragraph(f"<b>Generated Date:</b> {timezone.now().strftime('%b %d, %Y')}", styles["MetaRight"]),
        Paragraph(f"<b>Time:</b> {timezone.now().strftime('%H:%M:%S')}", styles["MetaRight"]),
        Paragraph(f"<b>Admin:</b> {_get_attr(admin_user, ['get_full_name', 'username'], 'System')}", styles["MetaRight"]),
    ]
    
    header_table = Table([[brand_block, meta_block]], colWidths=[100*mm, 70*mm])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
    ]))
    
    elements.extend([
        header_table,
        Spacer(1, 10),
        HRFlowable(width="100%", thickness=1.5, color=ACCENT_COLOR, spaceAfter=15)
    ])
    
    # --- STORE INFORMATION ---
    elements.append(Paragraph("STORE INFORMATION", styles["SectionHeading"]))
    store_info = [
        ("Store Name", _safe_str(getattr(seller, 'store_name', '—'))),
        ("Store Email", _safe_str(getattr(seller, 'store_email', '—'))),
        ("Store Slug", _safe_str(getattr(seller, 'slug', '—'))),
        ("Store Created", seller.created_at.strftime("%b %d, %Y") if getattr(seller, 'created_at', None) else "—"),
        ("Verification Status", _safe_str(getattr(seller, 'status', '—')).title()),
        ("Business Category", _safe_str(getattr(profile, 'business_category', '—'))),
        ("Website", _safe_str(getattr(profile, 'website', '—'))),
        ("Tax Number", _safe_str(getattr(settings, 'tax_id', '—'))),
        ("Registration No.", _safe_str(getattr(settings, 'business_registration_number', '—'))),
        ("", "")
    ]
    elements.extend([_build_kv_table(store_info, styles), Spacer(1, 15)])
    
    store_description = getattr(seller, 'store_description', None)
    if store_description:
        elements.extend([
            Paragraph("<b>Store Description:</b>", styles["KeyStyle"]),
            Spacer(1, 4),
            Paragraph(_safe_str(store_description), styles["NotesBody"]),
            Spacer(1, 15)
        ])

    # --- SELLER ACCOUNT ---
    elements.append(KeepTogether([
        Paragraph("SELLER ACCOUNT", styles["SectionHeading"]),
        _build_kv_table([
            ("Seller ID", _safe_str(getattr(seller, 'id', '—'))),
            ("User ID", _safe_str(getattr(user, 'id', '—'))),
            ("Username", _safe_str(getattr(user, 'username', '—'))),
            ("Account Status", _safe_str(getattr(user, 'account_status', 'Active')).title()),
            ("First Name", _safe_str(getattr(user, 'first_name', '—'))),
            ("Last Name", _safe_str(getattr(user, 'last_name', '—'))),
            ("Email", _safe_str(getattr(user, 'email', '—'))),
            ("Phone", _safe_str(getattr(user, 'contact', '—'))),
            ("Date Joined", user.date_joined.strftime("%b %d, %Y") if user and getattr(user, 'date_joined', None) else "—"),
            ("Last Login", user.last_login.strftime("%b %d, %Y %H:%M") if user and getattr(user, 'last_login', None) else "—"),
        ], styles)
    ]))
    elements.append(Spacer(1, 15))

    # --- BUSINESS ADDRESS ---
    elements.append(KeepTogether([
        Paragraph("BUSINESS ADDRESS", styles["SectionHeading"]),
        _build_kv_table([
            ("Country", "Pakistan"),
            ("City", _safe_str(getattr(address, 'city', '—'))),
            ("Postal Code", _safe_str(getattr(address, 'postal_code', '—'))),
            ("Address Line 1", _safe_str(getattr(address, 'address_line_1', '—'))),
            ("Address Line 2", _safe_str(getattr(address, 'address_line_2', '—'))),
            ("", "")
        ], styles)
    ]))
    elements.append(Spacer(1, 15))

    # --- SOCIAL MEDIA ---
    elements.append(KeepTogether([
        Paragraph("SOCIAL MEDIA", styles["SectionHeading"]),
        _build_kv_table([
            ("Facebook Label", _safe_str(getattr(profile, 'facebook_label', '—'))),
            ("Facebook URL", _safe_str(getattr(profile, 'facebook_url', '—'))),
            ("Instagram Label", _safe_str(getattr(profile, 'instagram_label', '—'))),
            ("Instagram URL", _safe_str(getattr(profile, 'instagram_url', '—'))),
            ("Twitter Label", _safe_str(getattr(profile, 'twitter_label', '—'))),
            ("Twitter URL", _safe_str(getattr(profile, 'twitter_url', '—'))),
            ("LinkedIn Label", _safe_str(getattr(profile, 'linkedin_label', '—'))),
            ("LinkedIn URL", _safe_str(getattr(profile, 'linkedin_url', '—'))),
        ], styles)
    ]))
    elements.append(Spacer(1, 15))

    # --- STORE PERFORMANCE ---
    now = timezone.now()
    first_day_this_month = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    last_day_prev_month = first_day_this_month - datetime.timedelta(days=1)
    first_day_prev_month = last_day_prev_month.replace(day=1, hour=0, minute=0, second=0, microsecond=0)

    prod_stats = Product.objects.filter(seller=seller).aggregate(
        total=Count('id'),
        published=Count('id', filter=Q(status__iexact='published')),
        draft=Count('id', filter=Q(status__iexact='draft')),
        hidden=Count('id', filter=Q(status__iexact='hidden')),
        out_of_stock=Count('id', filter=Q(stock_quantity__lte=0)),
        pending=Count('id', filter=Q(status__iexact='pending')),
        archived=Count('id', filter=Q(status__iexact='archived'))
    )

    ord_stats = Order.objects.filter(seller=seller).aggregate(
        total_orders=Count("id"),
        pending=Count("id", filter=Q(status__iexact='pending')),
        processing=Count("id", filter=Q(status__iexact='processing')),
        shipped=Count("id", filter=Q(status__iexact='shipped')),
        delivered=Count("id", filter=Q(status__iexact='delivered')),
        cancelled=Count("id", filter=Q(status__iexact='cancelled')),
        
        lifetime_rev=Coalesce(
            Sum("total", filter=~Q(status__iexact='cancelled')),
            0.0,
            output_field=FloatField(),
        ),
        
        monthly_rev=Coalesce(
            Sum(
                "total",
                filter=~Q(status__iexact='cancelled') & Q(created_at__gte=first_day_this_month),
            ),
            0.0,
            output_field=FloatField(),
        ),
        
        prev_monthly_rev=Coalesce(
            Sum(
                "total",
                filter=~Q(status__iexact='cancelled')
                & Q(created_at__gte=first_day_prev_month)
                & Q(created_at__lt=first_day_this_month),
            ),
            0.0,
            output_field=FloatField(),
        ),
    )
    
    lifetime_rev = float(ord_stats.get('lifetime_rev') or 0.0)
    monthly_rev = float(ord_stats.get('monthly_rev') or 0.0)
    prev_monthly_rev = float(ord_stats.get('prev_monthly_rev') or 0.0)
    total_orders = int(ord_stats.get('total_orders') or 0)
    total_cancelled = int(ord_stats.get('cancelled') or 0)

    growth = ((monthly_rev - prev_monthly_rev) / prev_monthly_rev * 100) if prev_monthly_rev > 0 else (100.0 if monthly_rev > 0 else 0.0)
    aov = (lifetime_rev / total_orders) if total_orders > 0 else 0.0
    refund_rate = (total_cancelled / total_orders * 100) if total_orders > 0 else 0.0

    elements.append(KeepTogether([
        Paragraph("STORE PERFORMANCE", styles["SectionHeading"]),
        _build_kv_table([
            ("Total Products", prod_stats.get('total', 0)), ("Total Orders", total_orders),
            ("Published Products", prod_stats.get('published', 0)), ("Pending Orders", ord_stats.get('pending', 0)),
            ("Draft Products", prod_stats.get('draft', 0)), ("Processing Orders", ord_stats.get('processing', 0)),
            ("Hidden Products", prod_stats.get('hidden', 0)), ("Shipped Orders", ord_stats.get('shipped', 0)),
            ("Out of Stock", prod_stats.get('out_of_stock', 0)), ("Delivered Orders", ord_stats.get('delivered', 0)),
            ("Pending Products", prod_stats.get('pending', 0)), ("Cancelled Orders", total_cancelled),
            ("Archived Products", prod_stats.get('archived', 0)), ("", ""),
            ("Lifetime Revenue", _format_currency(lifetime_rev)), ("Monthly Revenue", _format_currency(monthly_rev)),
            ("Previous Month Rev", _format_currency(prev_monthly_rev)), ("Revenue Growth", f"{growth:+.2f}%"),
            ("Average Order Value", _format_currency(aov)), ("Refund Rate", f"{refund_rate:.2f}%"),
        ], styles)
    ]))
    elements.append(Spacer(1, 15))

    # --- TOP PRODUCTS ---
    try:
        top_product_aggs = OrderItem.objects.filter(
            order__seller=seller,
            order__status__iexact='delivered'
        ).values(
            'product__name', 'product__category__name', 'product__status', 'product__stock_quantity'
        ).annotate(
            units_sold=Sum('quantity'),
            revenue=Sum('total')
        ).order_by('-revenue')[:10]
        
        top_products_data = [
            (
                _safe_str(p.get('product__name')),
                _safe_str(p.get('product__category__name', '—')),
                _safe_str(p.get('product__status', '—')).title(),
                str(p.get('product__stock_quantity', '0')),
                str(p.get('units_sold', 0)),
                _format_currency(p.get('revenue', 0))
            ) for p in top_product_aggs
        ]
    except Exception:
        top_product_aggs = OrderItem.objects.filter(
            order__seller=seller,
            order__status__iexact='delivered'
        ).values('product_id').annotate(
            units_sold=Sum('quantity'),
            revenue=Sum('total')
        ).order_by('-revenue')[:10]
        
        top_products_data = []
        product_ids = [p['product_id'] for p in top_product_aggs if p['product_id']]
        products_qs = Product.objects.filter(id__in=product_ids)
        product_dict = {p.id: p for p in products_qs}
        
        for p in top_product_aggs:
            prod = product_dict.get(p['product_id'])
            if prod:
                cat = getattr(prod, 'category', None)
                cat_name = getattr(cat, 'name', str(cat)) if cat else '—'
                top_products_data.append((
                    _safe_str(getattr(prod, 'name', 'Unknown')),
                    _safe_str(cat_name),
                    _safe_str(getattr(prod, 'status', '—')).title(),
                    str(getattr(prod, 'stock_quantity', '0')),
                    str(p.get('units_sold', 0)),
                    _format_currency(p.get('revenue', 0))
                ))
            else:
                top_products_data.append((
                    "Unknown Product", "—", "—", "0", 
                    str(p.get('units_sold', 0)), _format_currency(p.get('revenue', 0))
                ))

    elements.append(KeepTogether([
        Paragraph("TOP PRODUCTS", styles["SectionHeading"]),
        _build_data_table(
            headers=["Product", "Category", "Status", "Stock", "Sold", "Revenue"],
            row_data=top_products_data,
            col_widths=[55*mm, 35*mm, 20*mm, 15*mm, 15*mm, 30*mm],
            styles=styles,
            align_left_cols=[0, 1],
            align_right_cols=[4, 5]
        )
    ]))
    elements.append(Spacer(1, 15))

    # --- RECENT ORDERS ---
    recent_orders = Order.objects.filter(seller=seller).order_by('-created_at')[:10]
    recent_orders_data = []
    
    for order in recent_orders:
        tracking = getattr(order, 'tracking_number', None)
        if not tracking:
            tracking = getattr(order, 'order_number', str(order.id))
            
        customer = getattr(order, 'shipping_name', 'Unknown Customer')
        date_str = order.created_at.strftime("%b %d, %Y") if getattr(order, 'created_at', None) else "—"
        
        recent_orders_data.append((
            _safe_str(tracking),
            _safe_str(customer),
            date_str,
            _safe_str(getattr(order, 'status', '—')).title(),
            _format_currency(getattr(order, 'total', 0))
        ))

    elements.append(KeepTogether([
        Paragraph("RECENT ORDERS", styles["SectionHeading"]),
        _build_data_table(
            headers=["Order Number", "Customer", "Date", "Status", "Total"],
            row_data=recent_orders_data,
            col_widths=[35*mm, 50*mm, 30*mm, 25*mm, 30*mm],
            styles=styles,
            align_left_cols=[0, 1],
            align_right_cols=[4]
        )
    ]))
    elements.append(Spacer(1, 15))

    # --- TOP BUYERS ---
    try:
        top_buyers_qs = Order.objects.filter(seller=seller).exclude(status__iexact='cancelled').values(
            'shipping_name'
        ).annotate(
            orders_count=Count('id'),
            total_spent=Sum('total')
        ).order_by('-total_spent')[:10]
        
        top_buyers_data = [
            (
                _safe_str(b.get('shipping_name', 'Unknown')),
                str(b.get('orders_count', 0)),
                _format_currency(b.get('total_spent', 0))
            ) for b in top_buyers_qs
        ]
    except Exception:
        top_buyers_qs = Order.objects.filter(seller=seller).exclude(status__iexact='cancelled').values(
            'user_id'
        ).annotate(
            orders_count=Count('id'),
            total_spent=Sum('total')
        ).order_by('-total_spent')[:10]

        top_buyers_data = []
        for b in top_buyers_qs:
            uid = b.get('user_id')
            top_buyers_data.append((
                f"User #{uid}" if uid else "Unknown",
                str(b.get('orders_count', 0)),
                _format_currency(b.get('total_spent', 0))
            ))

    elements.append(KeepTogether([
        Paragraph("TOP BUYERS", styles["SectionHeading"]),
        _build_data_table(
            headers=["Buyer", "Orders", "Total Spent"],
            row_data=top_buyers_data,
            col_widths=[90*mm, 30*mm, 50*mm],
            styles=styles,
            align_left_cols=[0],
            align_right_cols=[1, 2]
        )
    ]))
    elements.append(Spacer(1, 15))

    # --- SHIPPING SETTINGS ---
    elements.append(KeepTogether([
        Paragraph("SHIPPING SETTINGS", styles["SectionHeading"]),
        _build_kv_table([
            ("Default Courier", _safe_str(getattr(settings, 'default_courier', '—'))),
            ("Handling Time", _safe_str(getattr(settings, 'default_handling_time', '—'))),
            ("Auto Mark Shipped", _yes_no(getattr(settings, 'auto_mark_shipped', False))),
            ("", ""),
            ("Return Address", _safe_str(getattr(settings, 'return_address', '—'))),
            ("", ""),
            ("Shipping Notes", _safe_str(getattr(settings, 'shipping_notes', '—'))),
            ("", ""),
        ], styles)
    ]))
    elements.append(Spacer(1, 15))

    # --- NOTIFICATION SETTINGS ---
    elements.append(KeepTogether([
        Paragraph("NOTIFICATION SETTINGS", styles["SectionHeading"]),
        _build_kv_table([
            ("Email New Order", _yes_no(getattr(settings, 'email_new_order', False))),
            ("Low Stock Alerts", _yes_no(getattr(settings, 'email_low_stock', False))),
            ("Email Cancelled", _yes_no(getattr(settings, 'email_cancelled_order', False))),
            ("Weekly Summary", _yes_no(getattr(settings, 'weekly_sales_summary', False))),
            ("Email Delivered", _yes_no(getattr(settings, 'email_delivered_order', False))),
            ("Monthly Report", _yes_no(getattr(settings, 'monthly_store_report', False))),
        ], styles)
    ]))
    elements.append(Spacer(1, 15))

    # --- ADMIN NOTES ---
    elements.append(KeepTogether([
        Paragraph("ADMIN NOTES", styles["SectionHeading"]),
    ]))
    notes = _safe_str(getattr(seller, 'verification_notes', ""))
    if notes and notes != "—":
        elements.append(Paragraph(notes.replace('\n', '<br/>'), styles["NotesBody"]))
    else:
        elements.append(Paragraph("<i>No admin notes available for this seller profile.</i>", styles["NotesBody"]))

    # Build PDF
    doc.build(elements, onFirstPage=_draw_footer, onLaterPages=_draw_footer)
    
    buffer.seek(0)
    date_str = timezone.now().strftime("%Y-%m-%d")
    safe_slug = str(getattr(seller, 'slug', getattr(seller, 'id', ''))).lower().replace(" ", "-")
    filename = f"seller-profile-snapshot-{safe_slug}-{date_str}.pdf"

    response = HttpResponse(buffer.getvalue(), content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    
    return response