# Generated by Django 6.0.6 on 2026-08-30 06:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_visibility', models.BooleanField(default=True)),
                ('search_visibility', models.BooleanField(default=True)),
                ('maximum_product_images', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('maximum_image_size_mb', models.PositiveSmallIntegerField(default=5, help_text='Maximum product image size in MB.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_confirm_orders', models.BooleanField(default=True)),
                ('allow_cancellation', models.BooleanField(default=True)),
                ('allow_order_notes', models.BooleanField(default=True)),
                ('allow_seller_notes', models.BooleanField(default=True)),
                ('cancellation_window', models.PositiveIntegerField(default=12, help_text='Hours')),
                ('return_window', models.PositiveIntegerField(default=7, help_text='Days')),
                ('order_number_format', models.CharField(default='MS-{YYYY}{#####}', max_length=50)),
                ('min_checkout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('guest_checkout', models.BooleanField(default=False)),
                ('require_email', models.BooleanField(default=True)),
                ('require_phone', models.BooleanField(default=True)),
                ('require_address', models.BooleanField(default=True)),
                ('tax_calculation', models.CharField(choices=[('none', 'None'), ('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='none', max_length=20)),
                ('shipping_calculation', models.CharField(choices=[('flat', 'Flat'), ('free', 'Free'), ('dynamic', 'Dynamic')], default='flat', max_length=20)),
                ('partial_orders', models.BooleanField(default=False)),
                ('split_orders', models.BooleanField(default=True)),
                ('backorders', models.BooleanField(default=False)),
                ('preorders', models.BooleanField(default=False)),
                ('order_hold', models.BooleanField(default=True)),
                ('fraud_review', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_online', models.BooleanField(default=True)),
                ('buyer_registration', models.BooleanField(default=True)),
                ('seller_registration', models.BooleanField(default=True)),
                ('guest_checkout', models.BooleanField(default=False)),
                ('multi_seller_orders', models.BooleanField(default=True)),
                ('seller_approval_required', models.BooleanField(default=True)),
                ('product_approval_required', models.BooleanField(default=False)),
                ('buyer_reviews', models.BooleanField(default=True)),
                ('seller_reviews', models.BooleanField(default=True)),
                ('featured_products', models.BooleanField(default=True)),
                ('featured_sellers', models.BooleanField(default=False)),
                ('featured_brands', models.BooleanField(default=False)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat'), ('tiered', 'Tiered')], default='percentage', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=8, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_order_amount', models.DecimalField(decimal_places=2, default=500000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_notifications', models.JSONField(default=dict)),
                ('seller_notifications', models.JSONField(default=dict)),
                ('admin_notifications', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_logo', models.ImageField(blank=True, null=True, upload_to='platform/')),
                ('marketplace_favicon', models.ImageField(blank=True, null=True, upload_to='platform/')),
                ('marketplace_name', models.CharField(default='MarketSphere', max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('marketplace_description', models.TextField(blank=True)),
                ('business_address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('support_url', models.URLField(blank=True)),
                ('privacy_url', models.URLField(blank=True)),
                ('terms_url', models.URLField(blank=True)),
                ('country', models.CharField(default='PK', max_length=2)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=50)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('language', models.CharField(default='en', max_length=10)),
                ('date_format', models.CharField(default='d/m/Y', max_length=30)),
                ('time_format', models.CharField(default='12', max_length=10)),
                ('business_registration_number', models.CharField(blank=True, max_length=50)),
                ('tax_registration_number', models.CharField(blank=True, max_length=50)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('setting_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
