# Generated by Django 6.0.6 on 2026-07-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
