# Generated by Django 6.0.6 on 2026-07-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
