# Generated by Django 6.0.6 on 2026-07-22 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('business', 'Business'), ('return', 'Return'), ('other', 'Other')], default='home', max_length=20),
        ),
        migrations.CreateModel(
            name='SellerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_courier', models.CharField(blank=True, max_length=100)),
                ('auto_mark_shipped', models.BooleanField(default=False)),
                ('shipping_notes', models.TextField(blank=True)),
                ('email_new_order', models.BooleanField(default=True)),
                ('email_cancelled_order', models.BooleanField(default=True)),
                ('email_delivered_order', models.BooleanField(default=True)),
                ('email_low_stock', models.BooleanField(default=True)),
                ('weekly_sales_summary', models.BooleanField(default=False)),
                ('monthly_store_report', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.seller')),
            ],
        ),
    ]
