# Generated by Django 6.0.6 on 2026-07-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_address_address_type_sellersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersettings',
            name='return_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('business', 'Business'), ('other', 'Other')], default='home', max_length=20),
        ),
    ]
