# Generated by Django 6.0.6 on 2026-07-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['-created_at'], 'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
        migrations.RemoveField(
            model_name='seller',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='seller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('deactivated', 'Deactivated'), ('suspended', 'Suspended'), ('blocked', 'Blocked'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Reason for rejection or notes from the admin.', null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='slug',
            field=models.SlugField(help_text='Unique URL for the seller store.', unique=True),
        ),
    ]
