# Generated by Django 6.0.6 on 2026-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_seller_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='store_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('bussiness', 'Bussiness'), ('other', 'Other')], default='home', max_length=20),
        ),
    ]
