# Generated by Django 6.0.6 on 2026-07-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sellersettings_return_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersettings',
            name='default_handling_time',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
