# Generated by Django 6.0.6 on 2026-07-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seller_store_email_alter_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('business', 'Business'), ('other', 'Other')], default='home', max_length=20),
        ),
    ]
