# Generated by Django 6.0.6 on 2026-07-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sellersettings_default_handling_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellersettings',
            name='default_handling_time',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 business day'), (2, '2 business days'), (3, '3 business days'), (5, '5 business days')], default=2),
        ),
    ]
