# Generated by Django 6.0.6 on 2026-07-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_sellerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='facebook',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='instagram',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='linkedin',
            new_name='linkedin_url',
        ),
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='x_twitter',
            new_name='twitter_url',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='facebook_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='instagram_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='linkedin_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='twitter_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
