# Generated by Django 6.0.6 on 2026-07-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_facebook_sellerprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersettings',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellersettings',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
