# Generated by Django 6.0.6 on 2026-08-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_sellerapplication_sellerapplicationdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='expected_monthly_volume',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='product_categories',
            field=models.CharField(blank=True, help_text='Comma-separated categories', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='years_in_business',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
