# Generated by Django 6.0.6 on 2026-08-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_sellerprofile_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersettings',
            name='address_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellersettings',
            name='bank_account_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellersettings',
            name='business_registration_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sellerapplicationdocument',
            name='document_type',
            field=models.CharField(choices=[('cnic_front', 'CNIC Front'), ('cnic_back', 'CNIC Back'), ('business_certificate', 'Business Registration Certificate'), ('ntn', 'NTN Certificate'), ('bank_statement', 'Bank Statement'), ('store_photo', 'Store Photo')], max_length=50),
        ),
    ]
