# Generated by Django 6.0.6 on 2026-08-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_sellersettings_address_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('verified', 'Verified'), ('deactivated', 'Deactivated'), ('suspended', 'Suspended'), ('blocked', 'Blocked'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='sellerapplicationdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='seller_documents/'),
        ),
    ]
