# Generated by Django 6.0.6 on 2026-09-08 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_seller_status_alter_sellerapplication_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_updates', models.BooleanField(default=True)),
                ('promotional_emails', models.BooleanField(default=True)),
                ('price_drop_alerts', models.BooleanField(default=True)),
                ('wishlist_alerts', models.BooleanField(default=True)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('review_reminders', models.BooleanField(default=True)),
                ('newsletter', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True, editable=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
