# Generated by Django 6.0.6 on 2026-09-12 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_remove_orderitem_seller_order_alter_order_options_and_more'),
        ('products', '0006_alter_brand_options_brand_country_of_origin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('contact', 'Contact Support'), ('problem', 'Report a Problem')], max_length=20)),
                ('category', models.CharField(choices=[('general', 'General Question'), ('order', 'Order'), ('delivery', 'Delivery'), ('payment', 'Payment'), ('product', 'Product'), ('seller', 'Seller'), ('account', 'Account'), ('technical', 'Technical'), ('feedback', 'Feedback / Suggestion'), ('other', 'Other')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=600)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support/attachments/')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App Response')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_for_user', 'Waiting for User'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=30)),
                ('admin_reply', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='orders.order')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='products.product')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_support_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-updated_at'], name='support_sup_user_id_7b0301_idx'), models.Index(fields=['request_type', 'status', '-created_at'], name='support_sup_request_b00d92_idx')],
            },
        ),
    ]
