# Generated by Django 6.0.6 on 2026-09-12 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='admin_reply',
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='related_product',
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='replied_at',
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='replied_by',
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='related_product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=20)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support/messages/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportrequest')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
