# Generated by Django 6.0.6 on 2026-07-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerorder',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='shipping_notes',
            field=models.TextField(blank=True),
        ),
    ]
