# Generated by Django 6.0.6 on 2026-08-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_sellerorder_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='notes',
            new_name='admin_notes',
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='seller_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
