# Generated by Django 6.0.6 on 2026-08-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_notes_order_admin_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='admin_notes',
            new_name='notes',
        ),
    ]
