# Generated by Django 6.0.6 on 2026-09-02 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_PROCESSING', 'Order Processing'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('WISHLIST_PRICE_DROP', 'Wishlist Price Drop'), ('LOW_STOCK', 'Low Stock'), ('SELLER_APPLICATION_APPROVED', 'Seller Application Approved'), ('SELLER_APPLICATION_REJECTED', 'Seller Application Rejected'), ('SYSTEM', 'System')], max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
