# Generated by Django 6.0.6 on 2026-09-03 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('ALL_USERS', 'All Users'), ('SELLER', 'Seller'), ('BUYER', 'Buyer'), ('ADMIN', 'Admin')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
