# Generated by Django 6.0.6 on 2026-07-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('hidden', 'Hidden'), ('out_of_stock', 'Out of Stock'), ('archived', 'Archived'), ('pending', 'Pending')], default='draft', max_length=20),
        ),
    ]
