# Generated by Django 6.0.6 on 2026-09-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_brand_options_brand_country_of_origin_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='products', through='promotions.PromotionProduct', to='promotions.promotion'),
        ),
    ]
