# Generated by Django 6.0.6 on 2026-09-16 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_promotions'),
        ('promotions', '0002_alter_promotion_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='promotion_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='promotions.promotionproduct'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('promotion_product__isnull', True)), fields=('cart', 'product'), name='unique_cart_product_normal'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('promotion_product__isnull', False)), fields=('cart', 'product', 'promotion_product'), name='unique_cart_product_promotion'),
        ),
    ]
